# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(937, 679)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.createNewPreset = QtWidgets.QPushButton(parent=self.centralwidget)
        self.createNewPreset.setGeometry(QtCore.QRect(230, 530, 91, 31))
        self.createNewPreset.setObjectName("createNewPreset")
        self.viewPresets = QtWidgets.QListView(parent=self.centralwidget)
        self.viewPresets.setGeometry(QtCore.QRect(705, 161, 161, 241))
        self.viewPresets.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.viewPresets.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAsNeeded)
        self.viewPresets.setResizeMode(QtWidgets.QListView.ResizeMode.Fixed)
        self.viewPresets.setObjectName("viewPresets")
        self.groupBoxSetup = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBoxSetup.setGeometry(QtCore.QRect(670, 120, 221, 361))
        self.groupBoxSetup.setObjectName("groupBoxSetup")
        self.runButton = QtWidgets.QPushButton(parent=self.groupBoxSetup)
        self.runButton.setGeometry(QtCore.QRect(30, 290, 75, 23))
        self.runButton.setIconSize(QtCore.QSize(16, 16))
        self.runButton.setObjectName("runButton")
        self.editButton = QtWidgets.QPushButton(parent=self.groupBoxSetup)
        self.editButton.setGeometry(QtCore.QRect(130, 290, 75, 23))
        self.editButton.setObjectName("editButton")
        self.importButton = QtWidgets.QPushButton(parent=self.groupBoxSetup)
        self.importButton.setGeometry(QtCore.QRect(30, 320, 75, 23))
        self.importButton.setObjectName("importButton")
        self.deleteButton = QtWidgets.QPushButton(parent=self.groupBoxSetup)
        self.deleteButton.setGeometry(QtCore.QRect(130, 320, 75, 23))
        self.deleteButton.setMouseTracking(False)
        self.deleteButton.setObjectName("deleteButton")
        self.quickSettingsButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.quickSettingsButton.setGeometry(QtCore.QRect(420, 530, 101, 31))
        self.quickSettingsButton.setObjectName("quickSettingsButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 937, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.createNewPreset.setText(_translate("MainWindow", "Create"))
        self.groupBoxSetup.setTitle(_translate("MainWindow", "Setups"))
        self.runButton.setText(_translate("MainWindow", "Run"))
        self.editButton.setText(_translate("MainWindow", "Edit"))
        self.importButton.setText(_translate("MainWindow", "Import"))
        self.deleteButton.setText(_translate("MainWindow", "Delete"))
        self.quickSettingsButton.setText(_translate("MainWindow", "Quick Settings"))
